apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dots
  name: env-configmap
data:
  mqtt-host: "mosquitto"
  mqtt-port: "1883"
  mqtt-qos: "0"
  influxdb-host: "influxdb"
  influxdb-port: "8086"
  influxdb-name: "GO-e"
  kubernetes-host: "kubernetes"
  kubernetes-port: "443"
  kubernetes-pull-image-secret-name: "ci-tno-dots"
  simulator-name: "dots-so"
  log-level: "INFO"
  influxdb-http-max-body-size: "0"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: dots
  name: env-secret
type: Opaque
data:
  mqtt-username: ZG90cw== # base64 encoded
  mqtt-password: ZG90c3Bhc3M= # base64 encoded
  influxdb-user: YWRtaW4= # 'admin' base64 encoded, also user for Grafana: Change for Azure!
  influxdb-password: YWRtaW4= # 'admin' base64 encoded, also used for Grafana: Change for Azure!
  secret-key: <<SECRET_KEY>>
  oauth-password: <<OAUTH_PASSWORD>>
  kubernetes-api-token: <<KUBE_API_TOKEN>

---
apiVersion: v1
kind: Secret
metadata:
  name: ci-tno-dots
  namespace: dots
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjaS50bm8ubmwiOnsidXNlcm5hbWUiOiJkb3RzLWRlcGxveS10b2tlbiIsInBhc3N3b3JkIjoiZXpZS3VIWXdLLVlaTmZmVXhnX3MiLCJhdXRoIjoiWkc5MGN5MWtaWEJzYjNrdGRHOXJaVzQ2WlhwWlMzVklXWGRMTFZsYVRtWm1WWGhuWDNNPSJ9fX0=

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dots
  name: mosquitto-config
data:
  mosquitto.conf: |
    max_queued_messages 0
    listener 1883 0.0.0.0
    allow_anonymous false
    password_file /mosquitto/config/mqtt_passwd
  mqtt_passwd: |
    dots:$7$101$pv4onIPwoTuoX/we$G6z9hs9ohtiSuKtCAjf2HuXOzUey7GbzzpFGZCcbfIJtRvEyv9ctfMuPfCLQu7JMMr3rJ4mAJ1iQDPXb1/E58Q==